host: 0.0.0.0
port: 8010
# log level: debug, info, warn, error, fatal
loglevel:
etcds:
  # first default
  - endpoints: 127.0.0.1:2379
    name: default
    separator: /
    tls:
      enable: false
      certFile:
      keyFile:
      trustedCAFile:
